<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CertificateManager" Version="4.0.3" />
    <PackageReference Include="AWSSDK.APIGateway" Version="4.0.3" />
    <PackageReference Include="AWSSDK.ApiGatewayV2" Version="4.0.3" />
    <PackageReference Include="AWSSDK.AppConfig" Version="4.0.3" />
    <PackageReference Include="AWSSDK.AppConfigData" Version="4.0.3" />
    <PackageReference Include="AWSSDK.AppSync" Version="4.0.3" />
    <PackageReference Include="AWSSDK.Athena" Version="4.0.3" />
    <PackageReference Include="AWSSDK.BedrockRuntime" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CloudFormation" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CloudWatch" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CloudFront" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CodeDeploy" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CostExplorer" Version="4.0.3" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.3" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.3" />
    <PackageReference Include="AWSSDK.EC2" Version="4.0.91" />
    <PackageReference Include="AWSSDK.ECR" Version="4.0.14.1" />
    <PackageReference Include="AWSSDK.ECS" Version="4.0.23.1" />
    <PackageReference Include="AWSSDK.ElastiCache" Version="4.0.5" />
    <PackageReference Include="AWSSDK.ElasticLoadBalancingV2" Version="4.0.3" />
    <PackageReference Include="AWSSDK.EventBridge" Version="4.0.3" />
    <PackageReference Include="AWSSDK.Glue" Version="4.0.3" />
    <PackageReference Include="AWSSDK.IdentityManagement" Version="4.0.3" />
    <PackageReference Include="AWSSDK.KeyManagementService" Version="4.0.3" />
    <PackageReference Include="AWSSDK.Kinesis" Version="4.0.3" />
    <PackageReference Include="AWSSDK.KinesisFirehose" Version="4.0.3" />
    <PackageReference Include="AWSSDK.Lambda" Version="4.0.17" />
    <PackageReference Include="AWSSDK.Pipes" Version="4.0.3" />
    <PackageReference Include="AWSSDK.RDS" Version="4.0.21" />
    <PackageReference Include="AWSSDK.Route53" Version="4.0.3" />
    <PackageReference Include="AWSSDK.ResourceGroupsTaggingAPI" Version="4.0.3" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.24" />
    <PackageReference Include="AWSSDK.Scheduler" Version="4.0.3.5" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.3" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="4.0.3" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.3" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.3" />
    <PackageReference Include="AWSSDK.StepFunctions" Version="4.0.3" />
    <PackageReference Include="AWSSDK.Textract" Version="4.0.3" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.3" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Testcontainers.Floci\Testcontainers.Floci.csproj" />
  </ItemGroup>

</Project>
